apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pandora
  description: Pandora Streaming Service
  tags:
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=pandora'
spec:
  type: service
  lifecycle: production
  owner: mapbu-team
